### PR TITLE
Added no-std testing to CI

### PR DESCRIPTION
**Pull request by fubuloubu**
Forgot to add `no-std` testing to our new CI!

### CODE REVIEW

**Comment by SRCoughlin** [comment]
This is showing the error `error: toolchain 'nightly-x86_64-unknown-linux-gnu' is not installed`
Is that easy to add?

**Comment by fubuloubu** [comment]
Working on that. I currently get this on my machine:
```
$ cargo +nightly build --no-default-features --features no-std
   Compiling untagged-option v0.1.1
   Compiling rustc-hex v2.0.1
   Compiling syn v0.15.35
   Compiling clap v2.33.0
error[E0740]: unions may not contain fields that need dropping
  --> /home/bryant/.cargo/registry/src/github.com-1ecc6299db9ec823/untagged-option-0.1.1/src/lib.rs:53:5
   |
53 |     pub some: T,
   |     ^^^^^^^^^^^
   |
note: `std::mem::ManuallyDrop` can be used to wrap the type
  --> /home/bryant/.cargo/registry/src/github.com-1ecc6299db9ec823/untagged-option-0.1.1/src/lib.rs:53:5
   |
53 |     pub some: T,
   |     ^^^^^^^^^^^

error: aborting due to previous error
```

I got it as far back as 68331e7

**Comment by SRCoughlin** [comment]
Yes, that's the same error I've been getting. Building `stable` shows an error with another package, so I'm not sure exactly what's going on.

**Comment by fubuloubu** [comment]
Nice, replicating it in CI now!

**Comment by fubuloubu** [comment]
@SRCoughlin now that everything is merged up, we can figure out what is going wrong in the `no-std` build

**Pull request merged**
